### ISSUE TITLE
[critical issue] too helpful

### ISSUE THREAD

**Issue by Reeses-Puffs** [spiralhalo/CanvasTutorial#1]
it seems your tutorial is so helpful that I might die from the helpfulness

**Comment by spiralhalo** [comment]
thank you for being a guinea pig for this potentially scuffed tutorial. unfortunately we can't address your issue. consider calling the 911 instead

**Comment by spiralhalo** [comment]
but seriously, thanks for giving it a try. I just want to make a low entry barrier introduction to canvas pipelines at first, but I'm starting to think that writing pipeline might be not so fun task after all. the more I try to explain advanced topic, the more I realize that I need to connect knowledge not only about canvas pipeline, but also rendering, logic, maths, and so on while *attempting* to make it look like low entry barrier fun activity.

so if you made it through chapter 4, congrats! i think it's still somewhat fun and games up to this point. if you wish to press on further.. well, good luck.

**Comment by spiralhalo** [comment]
I decided to identify the reason they weren't fun and rewrite chapter 5 a little..

At the end of the day most people probably don't recognize writing shaders are fun. But at the very least I want to make sure that I could have fun if I were to follow my own tutorial I guess.

Anyhow please keep giving feedback if you find yourself stuck. On the other meantime, I will keep revising it with my own feedback and then I will release it on Canvas showcase when it's ready.
